---
project_dir: ~/.script
downloads_dir: ~/Downloads

downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes
configure_npm: yes
configure_extra: yes
configure_dock: yes

dotfiles_repo: https://github.com/Mathew78540/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .gitignore
  - .osx
  - .vimrc
  - .zshrc.local

homebrew_installed_packages:
  - autoconf
  - automake
  - bash-completion
  - git
  - gpg
  - node
  - yarn
  - nvm
  - ssh-copy-id
  - wget
  - curl
  - mas
  - ncdu
  - scw
  - terminal-notifier
  - zsh
  - tree
  - dockutil
  - watch
  - zplug


homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - visual-studio-code
  - iterm2
  - spotify
  - docker
  - spectacle
  - beardedspice
  - vlc
  - appcleaner
  - dashlane

npm_global_package:
  - spaceship-zsh-theme

# See `geerlingguy.mas` role documentation for usage instructions.
mas_signin_dialog: yes
mas_installed_apps:
  - { id: 1091189122, name: "Bear" }
  - { id: 803453959, name: "Slack" }
  - { id: 409201541, name: "Pages" }
  - { id: 409183694, name: "Keynote" }

mas_upgrade_all_apps: yes

osx_script: "~/.osx --no-restart"

dockitems_disabled:
  - Launchpad
  - Siri
  - Mail
  - Safari
  - Contacts
  - Notes
  - Rappels
  - Maps
  - Photos
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendrier
  - Terminal
  - Plans
  - Pages
  - Numbers
  - Keynote
  - Préférences Système

dockitems_enabled:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Messages
    path: "/Applications/Messages.app"
    pos: 2
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 3
  - name: Slack
    path: "/Applications/Slack.app"
    pos: 4
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 5
  - name: Bear
    path: "/Applications/Bear.app"
    pos: 6
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 7
